window.__ModuleLoader__.load({
  id: 'dsh-agent-preset-editor',
  factory(require) {
    const React = require('react'), h = React.createElement, NS = 'dsh-agent-preset-editor';
    const zh = { open:'编辑 Agent 预设', title:'Agent 预设编辑器', preset:'预设', edit:'编辑现有预设', create:'复制为新预设', template:'模板',
      id:'预设 ID', name:'显示名称', description:'说明', order:'排序', persona:'人设段落', prefix:'前置人设提示词', suffix:'后置人设提示词',
      none:'新增人设段落', copy:'副本', save:'保存修改', add:'创建预设', close:'关闭', cancel:'取消', loading:'加载中…', saving:'正在保存…',
      saved:'已保存。新开启的任务使用更新后的预设。', created:'新预设已创建，可在 Agent 预设页面或新会话中选择。',
      hint:'正在运行的对话保留原来的配置。已有预设 ID 固定；显示名称可以随时修改。', idHint:'小写字母、数字和连字符；创建后固定。',
      conflict:'配置已变化，请重新加载后再保存。', reload:'重新加载', unavailable:'这份预设不属于可编辑的配置入口。',
      expression:'此人设由表达式生成，不能用文本编辑器覆盖。', choose:'选择预设', dirty:'有未保存的修改', stay:'继续编辑', discard:'放弃修改',
      notice:'预设 ID 关联已有对话；要换 ID，请复制为新预设。', broken:'预设加载失败', readOnly:'只读', default:'默认',
    };
    const en = { open:'Edit Agent presets', title:'Agent preset editor', preset:'Preset', edit:'Edit existing preset', create:'Copy to new preset', template:'Template',
      id:'Preset ID', name:'Display name', description:'Description', order:'Order', persona:'Persona section', prefix:'Prefix persona prompt', suffix:'Suffix persona prompt',
      none:'Add persona section', copy:'copy', save:'Save changes', add:'Create preset', close:'Close', cancel:'Cancel', loading:'Loading…', saving:'Saving…',
      saved:'Saved. Newly started tasks use the updated preset.', created:'Preset created. Choose it in Agent presets or when starting a new task.',
      hint:'Running conversations retain their configuration. Existing preset IDs stay fixed; display names can be changed.', idHint:'Lowercase letters, digits and hyphens; fixed after creation.',
      conflict:'Configuration changed. Reload before saving.', reload:'Reload', unavailable:'This preset has no editable configuration entry.',
      expression:'This persona is generated by an expression and cannot be overwritten as text.', choose:'Choose a preset', dirty:'Unsaved changes', stay:'Keep editing', discard:'Discard changes',
      notice:'Preset IDs are referenced by conversations. To use a different ID, copy this preset.', broken:'Activation error', readOnly:'Read-only', default:'Default',
    };
    const css = `
      .dpe-button{font:inherit;font-size:13px;line-height:20px;color:var(--dsw-alias-label-primary);background:var(--dsw-alias-bg-layer-2);border:1px solid var(--dsw-alias-border-l2);border-radius:var(--dsw-radius-md);padding:6px 12px;cursor:pointer}
      .dpe-button:hover:not(:disabled){background:var(--dsw-alias-interactive-bg-hover)}.dpe-button:disabled{opacity:.5;cursor:default}
      .dpe-backdrop{position:fixed;inset:0;z-index:1200;display:flex;align-items:center;justify-content:center;padding:24px;background:var(--dsw-alias-bg-mask-1);pointer-events:auto;box-sizing:border-box}
      .dpe-dialog{box-sizing:border-box;width:760px;max-width:100%;max-height:calc(100dvh - 48px);overflow:hidden;display:flex;flex-direction:column;border:1px solid var(--dsw-alias-border-l2);border-radius:var(--dsw-radius-panel);background:var(--dsw-alias-bg-layer-2);background:rgb(from var(--dsw-alias-bg-layer-2) r g b / 1);color:var(--dsw-alias-label-primary);font-family:inherit;font-size:14px;line-height:1.5;box-shadow:var(--dsw-elevation-prominent)}.dpe-dialog:focus{outline:none}
      .dpe-head{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:20px 24px 12px}.dpe-head h2{font-size:18px;margin:0;font-weight:600}
      .dpe-content{padding:0 24px 20px;overflow:auto;min-height:0}.dpe-muted{color:var(--dsw-alias-label-secondary);font-size:12px;margin:4px 0 12px}
      .dpe-tabs{display:flex;gap:8px;margin:8px 0 16px}.dpe-tabs [aria-pressed=true]{border-color:var(--dsw-alias-border-focusring);background:var(--dsw-alias-interactive-bg-hover)}
      .dpe-grid{display:grid;grid-template-columns:minmax(0,1fr) 110px;gap:12px}.dpe-field{display:flex;flex-direction:column;gap:6px;margin-bottom:12px}.dpe-field label{font-size:13px}
      .dpe-field input,.dpe-field select,.dpe-field textarea{box-sizing:border-box;max-width:100%;width:100%;font:inherit;font-size:13px;line-height:21px;background:var(--dsw-alias-bg-base);color:var(--dsw-alias-label-primary);border:1px solid var(--dsw-alias-border-l2);border-radius:var(--dsw-radius-md);padding:8px 10px}
      .dpe-field textarea{resize:vertical;min-height:100px}.dpe-field .dpe-prefix{min-height:180px}.dpe-field input[readonly]{color:var(--dsw-alias-label-secondary);background:var(--dsw-alias-bg-layer-2)}
      .dpe-dialog :is(input,select,textarea,button):focus-visible{outline:2px solid var(--dsw-alias-border-focusring);outline-offset:2px}
      .dpe-footer{display:flex;align-items:center;justify-content:flex-end;gap:10px;padding:14px 24px;border-top:1px solid var(--dsw-alias-border-l2)}
      .dpe-primary{background:var(--dsw-alias-label-primary);color:var(--dsw-alias-bg-base)}.dpe-primary:hover:not(:disabled){background:var(--dsw-alias-label-secondary)}
      .dpe-error{color:var(--dsw-alias-state-error-primary);white-space:pre-wrap;overflow-wrap:anywhere;margin:12px 0}.dpe-status{color:var(--dsw-alias-label-secondary);font-size:13px;margin:12px 0}
      .dpe-confirm{padding:12px;border:1px solid var(--dsw-alias-border-l2);border-radius:var(--dsw-radius-md);margin-bottom:12px;display:flex;align-items:center;justify-content:space-between;gap:10px}
      @media(max-width:560px){.dpe-backdrop{padding:12px}.dpe-dialog{max-height:calc(100dvh - 24px)}.dpe-content,.dpe-head,.dpe-footer{padding-left:16px;padding-right:16px}}
    `;
    async function request(action, value = {}) {
      const controller = new AbortController(), timer = setTimeout(() => controller.abort(), 30000);
      try {
        const carrier = window.__DSH_TRANSPORT__?.fetch ?? globalThis.fetch;
        const response = await carrier('/api/dsh-agent-preset-editor/' + action, { method:'POST', headers:{'content-type':'application/json'}, body:JSON.stringify(value), signal:controller.signal });
        const result = await response.json();
        if (!response.ok) throw new Error(result.error ?? String(response.status));
        return result;
      } finally { clearTimeout(timer); }
    }
    function editorStore() {
      let value = { open:false }, alive = true;
      const listeners = new Set();
      return { getSnapshot:()=>value, subscribe:fn=>{listeners.add(fn);return()=>listeners.delete(fn);},
        show(){if(!alive)return;value={open:true};for(const fn of listeners)fn();},
        close(){if(!alive)return;value={open:false};for(const fn of listeners)fn();},
        dispose(){alive=false;listeners.clear();},
      };
    }
    function Launcher({ store, t }) {
      const state=React.useSyncExternalStore(store.subscribe,store.getSnapshot);
      React.useEffect(()=>()=>store.close(),[store]);
      // Render within the native Settings action seat so its body-portaled modal
      // remains the owning focus and stacking context. The shell overlay is below Settings.
      return h(React.Fragment,null,h('style',null,css),h('button',{type:'button',className:'dpe-button',onClick:()=>store.show()},t('open')),
        state.open?h(Editor,{store,t}):null);
    }
    function Editor({ store, t }) {
      const root = React.useRef(null), titleId = React.useId(), alive = React.useRef(true), loadGeneration = React.useRef(0), requestBusy = React.useRef(false);
      const [rows,setRows] = React.useState([]), [selected,setSelected] = React.useState(''), [data,setData] = React.useState(null),
        [creating,setCreating] = React.useState(false), [busy,setBusy] = React.useState(true), [error,setError] = React.useState(''),
        [notice,setNotice] = React.useState(''), [draft,setDraft] = React.useState(null), [baseline,setBaseline] = React.useState(null),
        [pending,setPending] = React.useState(null);
      const dirty = draft !== null && JSON.stringify(draft) !== JSON.stringify(baseline);
      const dirtyRef = React.useRef(dirty); dirtyRef.current = dirty;
      const close = ()=>{if(requestBusy.current)return;if(dirtyRef.current)setPending(()=>()=>store.close());else store.close();};
      const closeRef = React.useRef(close); closeRef.current = close;
      React.useEffect(()=>{
        alive.current=true;
        const previous = document.activeElement, node=root.current;
        const focusables=()=>[...node.querySelectorAll('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled)')];
        node.focus();
        const key=event=>{
          if(event.key==='Escape'){event.preventDefault();event.stopPropagation();closeRef.current();}
          if(event.key==='Tab'){
            const controls=focusables(), first=controls[0], last=controls.at(-1);
            if(event.shiftKey&&(document.activeElement===first||!node.contains(document.activeElement))){event.preventDefault();last?.focus();}
            else if(!event.shiftKey&&(document.activeElement===last||!node.contains(document.activeElement))){event.preventDefault();first?.focus();}
          }
        };
        document.addEventListener('keydown',key,true);
        return()=>{alive.current=false;loadGeneration.current++;document.removeEventListener('keydown',key,true);if(previous?.isConnected)previous.focus();};
      },[store]);
      function changed(next) { setDraft(current=>({...current,...next}));setNotice(''); }
      function fromData(reply, mode) {
        const persona=reply.personas[0];
        return { id:mode?'':reply.id, name:mode?reply.name+' '+t('copy'):reply.name, description:reply.description, order:String(reply.order),
          personaPath:persona?.path??null, prefix:persona?.prefix??'', suffix:persona?.suffix??'' };
      }
      async function load(id, mode=creating) {
        const generation=++loadGeneration.current;setBusy(true);setError('');setNotice('');setData(null);setDraft(null);setBaseline(null);setSelected(id);setCreating(mode);
        try {
          const reply=await request('read',{id});
          if(!alive.current||generation!==loadGeneration.current)return;
          const next=fromData(reply,mode);setData(reply);setDraft(next);setBaseline(next);
        } catch(e) {if(alive.current&&generation===loadGeneration.current)setError(e.message);}
        finally {if(alive.current&&generation===loadGeneration.current)setBusy(false);}
      }
      React.useEffect(()=>{
        void (async()=>{try {
          const reply=await request('list');if(!alive.current)return;setRows(reply.presets);
          const row=reply.presets.find(row=>row.isDefault&&row.editable)??reply.presets.find(row=>row.editable);
          if(row)await load(row.id,false);else {setError(t('unavailable'));setBusy(false);}
        } catch(e){if(alive.current){setError(e.message);setBusy(false);}}})();
      },[]);
      function guarded(action) {if(busy)return;if(dirty)setPending(()=>action);else action();}
      async function save() {
        if(requestBusy.current||busy||!data||!draft)return;
        requestBusy.current=true;setBusy(true);setError('');setNotice('');
        try {
          const result=await request(creating?'create':'save',{...draft,revision:data.revision,template:selected,templateRevision:data.revision});
          if(!alive.current)return;
          const roster=await request('list');if(!alive.current)return;setRows(roster.presets);
          await load(result.id,false);if(alive.current)setNotice(t(creating?'created':'saved'));
        } catch(e){if(alive.current)setError(e.message);}
        finally {requestBusy.current=false;if(alive.current)setBusy(false);}
      }
      function field(key, label, kind='input', extra={}) {
        return h('div',{className:'dpe-field',key},h('label',{htmlFor:titleId+'-'+key},t(label)),h(kind,{id:titleId+'-'+key,value:draft?.[key]??'',disabled:busy,...extra,onChange:event=>changed({[key]:event.target.value})}));
      }
      const persona=data?.personas.find(row=>JSON.stringify(row.path)===JSON.stringify(draft?.personaPath));
      const writable=!persona||persona.editable;
      return h('div',{className:'dpe-backdrop',onPointerDown:event=>{if(event.target===event.currentTarget)close();}},
        h('section',{className:'dpe-dialog',ref:root,role:'dialog','aria-modal':true,'aria-labelledby':titleId,tabIndex:-1},
          h('div',{className:'dpe-head'},h('h2',{id:titleId},t('title')),h('button',{className:'dpe-button',type:'button',disabled:requestBusy.current,onClick:close,'aria-label':t('close')},'×')),
          h('div',{className:'dpe-content'},h('p',{className:'dpe-muted'},t('hint')),
            pending?h('div',{className:'dpe-confirm'},h('span',null,t('dirty')),h('button',{className:'dpe-button',onClick:()=>setPending(null)},t('stay')),
              h('button',{className:'dpe-button',onClick:()=>{const action=pending;setPending(null);action();}},t('discard'))):null,
            h('div',{className:'dpe-tabs'},[false,true].map(mode=>h('button',{type:'button',className:'dpe-button',key:String(mode),'aria-pressed':creating===mode,disabled:busy,onClick:()=>guarded(()=>load(selected,mode))},t(mode?'create':'edit')))),
            h('div',{className:'dpe-field'},h('label',{htmlFor:titleId+'-preset'},t(creating?'template':'preset')),
              h('select',{id:titleId+'-preset',value:selected,disabled:busy,onChange:event=>{const id=event.target.value;guarded(()=>load(id,creating));}},
                rows.map(row=>h('option',{key:row.id,value:row.id,disabled:!row.editable},`${row.name??row.id} · ${row.id}${row.isDefault?' · '+t('default'):''}${row.broken?' · '+t('broken'):''}${!row.editable?' · '+t('readOnly'):''}`)))),
            error?h('p',{className:'dpe-error',role:'alert'},error):null,
            notice?h('p',{className:'dpe-status',role:'status'},notice):null,
            busy&&!draft?h('p',{className:'dpe-status'},t('loading')):null,
            draft?h(React.Fragment,null,
              field('id','id','input',{readOnly:!creating,maxLength:80,placeholder:creating?'my-persona':undefined}),
              h('p',{className:'dpe-muted'},t(creating?'idHint':'notice')),
              h('div',{className:'dpe-grid'},field('name','name','input',{maxLength:200}),field('order','order','input',{type:'number',step:'any'})),
              field('description','description','input',{maxLength:4000}),
              data.personas.length>1?h('div',{className:'dpe-field'},h('label',{htmlFor:titleId+'-persona'},t('persona')),
                h('select',{id:titleId+'-persona',disabled:busy,value:JSON.stringify(draft.personaPath),onChange:event=>{
                  const row=data.personas.find(row=>JSON.stringify(row.path)===event.target.value);
                  guarded(()=>{const next={...baseline,personaPath:row.path,prefix:row.prefix,suffix:row.suffix};setDraft(next);setBaseline(next);});
                }},data.personas.map(row=>h('option',{key:JSON.stringify(row.path),value:JSON.stringify(row.path)},row.id)))):null,
              !writable?h('p',{className:'dpe-error'},t('expression')):null,
              field('prefix','prefix','textarea',{className:'dpe-prefix',readOnly:!writable,spellCheck:false}),
              field('suffix','suffix','textarea',{readOnly:!writable,spellCheck:false}),
            ):null),
          h('div',{className:'dpe-footer'},h('button',{type:'button',className:'dpe-button',disabled:busy,onClick:()=>guarded(()=>load(selected,creating))},t('reload')),
            h('button',{type:'button',className:'dpe-button',disabled:requestBusy.current,onClick:close},t('close')),
            h('button',{type:'button',className:'dpe-button dpe-primary',disabled:busy||!draft||!writable||!draft.name.trim()||(creating?!/^[a-z0-9]+(?:-[a-z0-9]+)*$/u.test(draft.id):!dirty),onClick:()=>void save()},t(busy?'saving':creating?'add':'save')))));
    }
    function apply(ctx) {
      ctx.effect(()=>ctx.locale.register(NS,{zh,en}), 'persona-editor: dictionaries');
      const t=ctx.locale.bind(NS), store=editorStore();
      ctx.effect(()=>()=>store.dispose(), 'persona-editor: view state');
      ctx.effect(()=>ctx.slots.inject('settings.action',()=>ctx.slots.register({name:'settings.action',id:NS,order:10,locale:NS,inject:()=>({store,t})},Launcher)), 'persona-editor: native settings action');
    }
    return { apply, inject:['slots','locale'], request, editorStore };
  },
});
